"""Add versioning settings table

Revision ID: 8e7b7a2c330c
Revises: 879d664cd06e
Create Date: 2025-08-06 23:00:45.518371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e7b7a2c330c'
down_revision = '879d664cd06e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('versioning_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('auto_version_enabled', sa.Boolean(), nullable=True),
    sa.Column('auto_version_on_record_change', sa.Boolean(), nullable=True),
    sa.Column('auto_version_on_zone_change', sa.Boolean(), nullable=True),
    sa.Column('max_versions_per_zone', sa.Integer(), nullable=True),
    sa.Column('version_retention_days', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_versioning_settings_id'), 'versioning_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_versioning_settings_id'), table_name='versioning_settings')
    op.drop_table('versioning_settings')
    # ### end Alembic commands ###
